/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompletaRouteImport } from './routes/completa'
import { Route as IndexRouteImport } from './routes/index'

const CompletaRoute = CompletaRouteImport.update({
  id: '/completa',
  path: '/completa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completa': typeof CompletaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completa': typeof CompletaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completa': typeof CompletaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/completa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/completa'
  id: '__root__' | '/' | '/completa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletaRoute: typeof CompletaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/completa': {
      id: '/completa'
      path: '/completa'
      fullPath: '/completa'
      preLoaderRoute: typeof CompletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletaRoute: CompletaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
